services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ddd
      POSTGRES_PASSWORD: sample
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: